repos:
  - repo: local
    hooks:
      - id: sync-dependencies
        name: Sync dependencies
        entry: python sync_dependencies.py
        language: system
        files: ^(requirements.txt|pyproject.toml)$
