repos:
  - repo: local
    hooks:
      - id: Update dependencies
        name: Update dependencies
        entry: python update_dependencies.py
        language: system
        files: ^(requirements.txt|pyproject.toml)$
